from django.db import models

"""
# Mini ejemplo 

class Person(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

CREATE TABLE myapp_person (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "first_name" varchar(30) NOT NULL,
    "last_name" varchar(30) NOT NULL
);

#Cabe aclarar que aun no tengo muy claro si es necesario lo de class y tambien el create table ya que en postgresql es diferente 
"""




# Create your models here.
